"""
MEMOIR Core Data Models
-----------------------
MemoryEntry, EpistemicTag, AuditRecord, DriftReport

These models are the schema contract for the entire system.
Everything flows through here.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, ConfigDict, field_validator


# ---------------------------------------------------------------------------
# Epistemic Classification
# ---------------------------------------------------------------------------

class EpistemicTag(str, Enum):
    """
    Confidence classification for every memory entry.

    VERIFIED              -- checked against source and confirmed
    USER_STATED           -- direct claim or instruction from the user
    INFERRED              -- derived from verified memories via reasoning
    ASSUMED               -- agent-generated without verification
    STALE                 -- previously verified but TTL exceeded
    REJECTED              -- failed critique; not written
    AGENT_DERIVED         -- conclusions the agent reached through analysis
    METACOGNITIVE_INSIGHT -- generated by ORACLE self-reflection loop
    """
    VERIFIED = "VERIFIED"
    USER_STATED = "USER_STATED"
    INFERRED = "INFERRED"
    ASSUMED  = "ASSUMED"
    STALE    = "STALE"
    REJECTED = "REJECTED"
    AGENT_DERIVED = "AGENT_DERIVED"
    METACOGNITIVE_INSIGHT = "METACOGNITIVE_INSIGHT"


class CritiqueVerdict(str, Enum):
    """Outcome of the secondary critique agent pass."""
    PASS     = "PASS"      # Write approved
    FLAG     = "FLAG"      # Write approved with warning attached
    REJECT   = "REJECT"    # Write blocked


# ---------------------------------------------------------------------------
# Memory Entry
# ---------------------------------------------------------------------------

class MemoryEntry(BaseModel):
    """
    A single memory unit proposed for storage.

    This is the object that enters MEMOIR's validation pipeline.
    On exit it carries its epistemic tag, critique verdict, and audit ID.
    """
    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_assignment=True,
        extra="forbid",
    )

    # Identity
    entry_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for this memory entry"
    )
    session_id: str = Field(
        ...,
        description="Session that generated this entry (e.g., Claude Code session ID)",
        min_length=1,
    )
    agent_id: Optional[str] = Field(
        default=None,
        description="Sub-agent identifier if generated by a worker agent"
    )

    # Content
    key: str = Field(
        ...,
        description="Memory key (maps to MEMORY.md pointer index)",
        min_length=1,
        max_length=200,
    )
    content: str = Field(
        ...,
        description="The belief or fact the agent wants to record",
        min_length=1,
        max_length=4000,
    )
    source_reference: Optional[str] = Field(
        default=None,
        description="File path, URL, or document reference the agent claims this derives from"
    )

    # Provenance
    tool_call_id: Optional[str] = Field(
        default=None,
        description="Tool call that produced this memory entry"
    )
    triggering_input: Optional[str] = Field(
        default=None,
        description="The agent input that led to this memory write (truncated)"
    )
    human_session_context: Optional[str] = Field(
        default=None,
        description="Human authorization context: who was present, what they requested"
    )

    # Timestamps
    proposed_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When the agent proposed this write"
    )

    # Classification (populated by MEMOIR pipeline)
    epistemic_tag: Optional[EpistemicTag] = Field(
        default=None,
        description="Confidence classification assigned by MEMOIR classifier"
    )
    critique_verdict: Optional[CritiqueVerdict] = Field(
        default=None,
        description="Outcome of secondary critique agent pass"
    )
    critique_notes: Optional[str] = Field(
        default=None,
        description="Critique agent reasoning and any flagged contradictions"
    )
    verified_at: Optional[datetime] = Field(
        default=None,
        description="When ground truth verification was performed (VERIFIED entries only)"
    )
    stale_after: Optional[datetime] = Field(
        default=None,
        description="Datetime after which this entry should be reclassified as STALE"
    )

    @field_validator("content")
    @classmethod
    def content_not_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Memory content cannot be empty or whitespace only")
        return v


# ---------------------------------------------------------------------------
# Audit Record
# ---------------------------------------------------------------------------

class AuditRecord(BaseModel):
    """
    Immutable log entry for every memory operation.

    Written once, never modified. Queryable by session, tag, time, or key.
    This is the SAF continuous observability layer made concrete.
    """
    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_assignment=True,
        extra="forbid",
    )

    audit_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique audit record identifier"
    )
    entry_id: str = Field(
        ...,
        description="MemoryEntry this record corresponds to"
    )
    session_id: str = Field(..., description="Originating session")
    key: str = Field(..., description="Memory key operated on")
    content: Optional[str] = Field(default=None, description="Belief content text")

    operation: str = Field(
        ...,
        description="Operation type: WRITE_APPROVED, WRITE_FLAGGED, WRITE_REJECTED, READ, STALE_DETECTED"
    )

    epistemic_tag: EpistemicTag = Field(..., description="Final tag assigned")
    critique_verdict: CritiqueVerdict = Field(..., description="Critique outcome")
    critique_notes: Optional[str] = Field(default=None)

    source_reference: Optional[str] = Field(default=None)
    tool_call_id: Optional[str] = Field(default=None)
    human_session_context: Optional[str] = Field(default=None)

    recorded_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When this audit record was written"
    )

    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional structured metadata (latency, model used, token count, etc.)"
    )


# ---------------------------------------------------------------------------
# Drift Report
# ---------------------------------------------------------------------------

class DriftEvent(BaseModel):
    """A single detected divergence between memory and ground truth."""
    key: str
    memory_content: str
    actual_content: str
    drift_type: str  # CONTRADICTION, STALE, MISSING_SOURCE
    severity: str    # LOW, MEDIUM, HIGH
    detected_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class DriftReport(BaseModel):
    """
    Behavioral drift report for a session or time window.

    Compares current memory state against actual source material.
    Surfaces the gap between what the agent believes and what is true.
    """
    model_config = ConfigDict(extra="forbid")

    report_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    session_id: Optional[str] = Field(default=None, description="Session scoped to, or None for global")
    window_start: datetime
    window_end: datetime

    total_entries_checked: int = Field(ge=0)
    drift_events: List[DriftEvent] = Field(default_factory=list)
    drift_rate: float = Field(ge=0.0, le=1.0, description="Fraction of entries with detected drift")

    stale_count: int = Field(default=0, ge=0)
    contradiction_count: int = Field(default=0, ge=0)
    missing_source_count: int = Field(default=0, ge=0)

    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    summary: Optional[str] = Field(default=None, description="Human-readable drift summary")


# ---------------------------------------------------------------------------
# Pipeline Result
# ---------------------------------------------------------------------------

class ValidationResult(BaseModel):
    """
    Full output of the MEMOIR validation pipeline for a single MemoryEntry.
    Returned to the caller (agent or MCP tool) after processing.
    """
    model_config = ConfigDict(extra="forbid")

    entry_id: str
    audit_id: str
    approved: bool
    epistemic_tag: EpistemicTag
    critique_verdict: CritiqueVerdict
    critique_notes: Optional[str] = None
    latency_ms: Optional[float] = None
    message: str = Field(description="Human-readable summary of the pipeline outcome")


# ---------------------------------------------------------------------------
# Belief Types (for MIRROR and ORACLE systems)
# ---------------------------------------------------------------------------

class BeliefType(str, Enum):
    """
    I'm tracking where beliefs come from so we can reason about provenance.
    STANDARD is the default; the others get set by specific subsystems.
    """
    STANDARD = "STANDARD"
    MIRROR_REFLECTION = "MIRROR_REFLECTION"
    SYSTEM_DERIVED = "SYSTEM_DERIVED"
    AGENT_DERIVED = "AGENT_DERIVED"
    METACOGNITIVE_INSIGHT = "METACOGNITIVE_INSIGHT"


# ---------------------------------------------------------------------------
# BQS (Belief Quality Score) Model
# ---------------------------------------------------------------------------

class BQSScore(BaseModel):
    """
    Belief Quality Score computed by the ORACLE engine.
    Five dimensions, each 0.0-1.0, weighted into a composite score.
    I chose these weights based on what matters most for epistemic trust.
    """
    model_config = ConfigDict(extra="forbid")

    entry_id: str
    session_id: str

    source_reliability: float = Field(ge=0.0, le=1.0, description="Historical accuracy of this source")
    verification_depth: float = Field(ge=0.0, le=1.0, description="How thoroughly was this belief verified?")
    tag_confidence: float = Field(ge=0.0, le=1.0, description="How appropriate was the epistemic classification?")
    temporal_freshness: float = Field(ge=0.0, le=1.0, description="Age relative to TTL, 1.0 = just verified")
    critique_concordance: float = Field(ge=0.0, le=1.0, description="Did critique agree with classification?")

    composite_score: float = Field(ge=0.0, le=1.0, description="Weighted BQS composite")
    computed_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @classmethod
    def compute(
        cls,
        entry_id: str,
        session_id: str,
        source_reliability: float,
        verification_depth: float,
        tag_confidence: float,
        temporal_freshness: float,
        critique_concordance: float,
    ) -> "BQSScore":
        """Weighted composite: the weights reflect my prioritization of source trust."""
        composite = (
            0.25 * source_reliability
            + 0.20 * verification_depth
            + 0.20 * tag_confidence
            + 0.20 * temporal_freshness
            + 0.15 * critique_concordance
        )
        return cls(
            entry_id=entry_id,
            session_id=session_id,
            source_reliability=source_reliability,
            verification_depth=verification_depth,
            tag_confidence=tag_confidence,
            temporal_freshness=temporal_freshness,
            critique_concordance=critique_concordance,
            composite_score=round(min(max(composite, 0.0), 1.0), 4),
        )


# ---------------------------------------------------------------------------
# CPI (Cognitive Pressure Index) Model
# ---------------------------------------------------------------------------

class CPISignals(BaseModel):
    """Raw signal values feeding into CPI computation."""
    model_config = ConfigDict(extra="forbid")

    epistemic_drift_rate: float = Field(ge=0.0, le=1.0)
    source_citation_drop: float = Field(ge=0.0, le=1.0)
    contradiction_tolerance: float = Field(ge=0.0, le=1.0)
    ttl_violation_rate: float = Field(ge=0.0, le=1.0)
    confidence_accuracy_gap: float = Field(ge=0.0, le=1.0)
    decision_velocity: float = Field(ge=0.0, le=1.0)


class CPIScore(BaseModel):
    """
    Cognitive Pressure Index score for a session.
    I'm using 6 behavioral proxy signals to detect when an agent is under pressure.
    """
    model_config = ConfigDict(extra="forbid")

    session_id: str
    signals: CPISignals
    composite_score: float = Field(ge=0.0, le=1.0)
    intervention_level: str = Field(description="GREEN, YELLOW, ORANGE, or RED")
    window_size: int = Field(description="Number of beliefs in the sliding window")
    computed_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @classmethod
    def compute(cls, session_id: str, signals: CPISignals, window_size: int) -> "CPIScore":
        """Weighted CPI from 6 signals. Thresholds drive intervention levels."""
        composite = (
            0.25 * signals.epistemic_drift_rate
            + 0.20 * signals.source_citation_drop
            + 0.20 * signals.contradiction_tolerance
            + 0.15 * signals.ttl_violation_rate
            + 0.10 * signals.confidence_accuracy_gap
            + 0.10 * signals.decision_velocity
        )
        composite = round(min(max(composite, 0.0), 1.0), 4)

        if composite < 0.3:
            level = "GREEN"
        elif composite < 0.5:
            level = "YELLOW"
        elif composite < 0.7:
            level = "ORANGE"
        else:
            level = "RED"

        return cls(
            session_id=session_id,
            signals=signals,
            composite_score=composite,
            intervention_level=level,
            window_size=window_size,
        )


# ---------------------------------------------------------------------------
# Conflict Detection Models
# ---------------------------------------------------------------------------

class ConflictType(str, Enum):
    DIRECT_CONTRADICTION = "DIRECT_CONTRADICTION"
    TEMPORAL_CONFLICT = "TEMPORAL_CONFLICT"
    SOURCE_DISAGREEMENT = "SOURCE_DISAGREEMENT"
    RULE_VIOLATION = "RULE_VIOLATION"


class ResolutionStrategy(str, Enum):
    HIGHER_BQS_WINS = "HIGHER_BQS_WINS"
    NEWER_VERIFIED_WINS = "NEWER_VERIFIED_WINS"
    USER_STATED_PRIORITY = "USER_STATED_PRIORITY"
    ESCALATE_TO_HUMAN = "ESCALATE_TO_HUMAN"


class ConflictRecord(BaseModel):
    """
    Tracks a detected conflict between two beliefs.
    I want to capture both the conflict and how it was resolved
    so ORACLE can learn from the pattern.
    """
    model_config = ConfigDict(extra="forbid")

    conflict_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    session_id: str
    belief_a_id: str
    belief_b_id: str
    conflict_type: ConflictType
    resolution_strategy: ResolutionStrategy
    winner_id: Optional[str] = None
    description: str
    resolved: bool = False
    resolved_at: Optional[datetime] = None
    detected_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ---------------------------------------------------------------------------
# ORACLE Report and Metacognitive Insight
# ---------------------------------------------------------------------------

class MetacognitiveInsight(BaseModel):
    """
    A single insight generated by ORACLE's self-reflection loop.
    These get written back as METACOGNITIVE_INSIGHT belief types.
    """
    model_config = ConfigDict(extra="forbid")

    insight_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    session_id: str
    cycle_id: str
    category: str = Field(description="e.g. 'recurring_rejection', 'source_degradation', 'calibration_drift'")
    description: str
    severity: str = Field(description="LOW, MEDIUM, HIGH")
    affected_entries: List[str] = Field(default_factory=list)
    recommendation: str
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class OracleReport(BaseModel):
    """
    Full output of an ORACLE analysis cycle for a session.
    Contains BQS scores, pattern analysis, and generated insights.
    """
    model_config = ConfigDict(extra="forbid")

    report_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    session_id: str
    cycle_id: str
    audit_range_start: datetime
    audit_range_end: datetime
    total_entries_analyzed: int = Field(ge=0)
    bqs_scores: List[BQSScore] = Field(default_factory=list)
    avg_bqs: float = Field(ge=0.0, le=1.0, default=0.0)
    insights: List[MetacognitiveInsight] = Field(default_factory=list)
    source_weight_updates: Dict[str, float] = Field(default_factory=dict)
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
